backend:
  name: git-gateway

media_folder: 'assets/images/uploads'

collections:
  - name: 'guide'
    label: 'Guide'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'guide' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Sections'
        name: 'sections'
        widget: 'list'
        fields:
          - { label: 'Heading', name: 'heading', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Image Steps'
            name: 'imageSteps'
            widget: 'list'
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Paragraph', name: 'paragraph', widget: 'text' }
